version: '3.8'

services:
  kma_score:
    container_name: kma_score
    image: arahiko/kma-score-api:latest
    env_file:
      - ./.env
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MEILISEARCH_HOST=${MEILISEARCH_HOST}
      - MEILISEARCH_PORT=${MEILISEARCH_PORT}
      - MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY}
      - JWT_CLIENT_PUBLIC_KEY=${JWT_CLIENT_PUBLIC_KEY}
      - JWT_SERVER_PRIVATE_KEY=${JWT_SERVER_PRIVATE_KEY}
    links:
        - meilisearch
    networks:
      - proxy

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY}
      - MEILI_NO_ANALYTICS=${MEILISEARCH_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILISEARCH_ENV:-production}
      - MEILI_DB_PATH=${MEILISEARCH_DB_PATH:-/data.ms}
    networks:
      - proxy

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: "cloudflared_proxy"
