version: '3.8'

services:
  kma_score:
    container_name: kma_score
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:8080
    volumes:
      - ./cert:/app/cert
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ENABLE_SSL=${ENABLE_SSL}