name: Deploy to VPS

on:
  push:
    tags:
      - "**"

jobs:
  build:
    uses: ./.github/workflows/docker-img.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            cd /tp-share/kma_score_api
            git pull
            docker compose pull
            docker compose -f docker-compose.npm.yml up -d
