name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kma-score-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kma-score-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kma-score-api:buildcache,mode=max